-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 19:38:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Entertainment-Club
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Entertainment-Club` ;

-- -----------------------------------------------------
-- Schema Entertainment-Club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Entertainment-Club` DEFAULT CHARACTER SET utf8 ;
USE `Entertainment-Club` ;

-- -----------------------------------------------------
-- Table `Entertainment-Club`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `max_guests` INT NOT NULL DEFAULT 5,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NULL,
  `surnames` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`datetimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`datetimes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `room_id`),
  INDEX `fk_datetimes_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_datetimes_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `Entertainment-Club`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id1` INT NOT NULL,
  `room_id` INT NOT NULL,
  `datetime_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id1`, `room_id`, `datetime_id`),
  INDEX `fk_reservations_user1_idx` (`user_id1` ASC) VISIBLE,
  INDEX `fk_reservations_rooms1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_reservations_datetimes1_idx` (`datetime_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_user1`
    FOREIGN KEY (`user_id1`)
    REFERENCES `Entertainment-Club`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `Entertainment-Club`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_datetimes1`
    FOREIGN KEY (`datetime_id`)
    REFERENCES `Entertainment-Club`.`datetimes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `min_players` INT NOT NULL DEFAULT 1,
  `max_players` INT NOT NULL,
  `description` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`id`, `game_id`),
  INDEX `fk_inventory_games_idx` (`game_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_games`
    FOREIGN KEY (`game_id`)
    REFERENCES `Entertainment-Club`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entertainment-Club`.`reservations_has_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entertainment-Club`.`reservations_has_inventory` (
  `reservation_id` INT NOT NULL,
  `inventory_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`, `inventory_id`),
  INDEX `fk_reservations_has_inventory_inventory1_idx` (`inventory_id` ASC) VISIBLE,
  INDEX `fk_reservations_has_inventory_reservations1_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_has_inventory_reservations1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `Entertainment-Club`.`reservations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_has_inventory_inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `Entertainment-Club`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
